name: real_estate_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  get: ^4.7.3
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.8
  dio: ^5.9.1
  flutter_svg: ^2.2.3
  logger: ^2.6.2
  flutter_secure_storage: ^10.0.0
  carousel_slider: ^5.1.2
  syncfusion_flutter_sliders: ^32.2.5
  dropdown_flutter: ^1.0.3
  shimmer: ^3.0.0
  intl: ^0.20.2
  video_player: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/icons/ 
    - .env.development
